#!/usr/bin/env python
# coding=utf-8
"""
The file contains the project constant variables.
"""

LOCAL_HOST = 'localhost'
LOCAL_RECEIVE_TUPLE = ['@' + LOCAL_HOST]

STEP_SUCCESS = 0
STEP_REDO = 1
STEP_FAILED = -1

VERIFY_INS_DATA = 'data'
VERIFY_INS_BAKSET = 'bakset'
VERIFY_BAKSET_SUCCESS = 0
VERIFY_BAKSET_FAILED = -1
VERIFY_BAKSET_TIMEOUT = 0x7f
MSG_VERIFY_BAKSET_SUCCESS = "success"
MYSQL_VERSION_SUPPORT_CHANNEL = "20150330"

MYSQL_VERSION_SUPPORT_PARALLEL_WORKER = "20150817"

######################## pipeline ###############################

PIPELINE_FAILED =  -1
PIPELINE_SUCCESS = 0
PIPELINE_CONTINUE = 1

CREATING_ACCOUNT = 0
ACTIVE_ACCOUNT = 1
DELETING_ACCOUNT = 3
DEALING_ACCOUNT = 4

CREATING_DB = 0
ACTIVE_DB = 1
DELETING_DB = 3

CREATING_ACCOUNT_DB_REL = 0
ACTIVE_ACCOUNT_DB_REL = 1
DELETING_ACCOUNT_DB_REL = 3

AURORA_DNS_HA='dns'
AURORA_F5_HA='f5'
AURORA_LVS_HA='lvs'
AURORA_PROXY_HA='proxy'
AURORA_PHYSICAL_HA = "physical"

#########################################################
# define net_type
#########################################################
NET_TYPE_INTERNET = 0
NET_TYPE_INTRANET = 1
NET_TYPE_VPC = 2

PROXY_HA_STATE_NOSWITCH = "no_switch"
PROXY_HA_STATE_SWITCHING = "switching"

AURORA_LVS_MODE_DR = 'DR'
AURORA_LVS_MODE_DNAT = 'DNAT'

AURORA_SLB_VER_V1 = '1'
AURORA_SLB_VER_V2 = '2'

ACCOUNT_MODE_NORMAL = 0
ACCOUNT_MODE_UPGRADABLE = 1
ACCOUNT_MODE_UPGRADE = 2

NEW_ACCOUNT_MODE_NORMAL = 3
NEW_ACCOUNT_MODE_UPGRADABLE = 4
NEW_ACCOUNT_MODE_UPGRADE = 5

CUSTINS_NEW_ACCOUNT_MODES = {NEW_ACCOUNT_MODE_NORMAL,
                             NEW_ACCOUNT_MODE_UPGRADABLE,
                             NEW_ACCOUNT_MODE_UPGRADE}
UPGRADE_ACCOUNT_MODES = {ACCOUNT_MODE_UPGRADE, NEW_ACCOUNT_MODE_UPGRADE}


################### tuning mysql settings #################################
RULE_SQL_EXEC_COUNT = 10
RULE_SQL_MAX_LATENCY = 5000  #us
RULE_TABLE_MIN_SIZE = 1000 # must large below
RULE_TABLE_SAMPLE_NUM = 1000
RULE_TABLE_SAMPE_PER = 10   # 10%
RULE_COLUMN_CARD = 70
RULE_INDEX_COUNT_MAX = 4
TIMED_TUNING = 'TIMEDTUNING'
REAL_TUNING = 'REALTUNING'
APP_KEY = 'RDS'
MESSAGEID = '0000'
LINKPIN = '0000'
TUNNING_ACS_CFB_KEY = '13IUTri72vDSn6Af'
TUNNING_ACS_CFB_IV = 'q9vc5HLbDpKng12A'

####################### PACKAGE STATUS CODES #########################

# HTTP Status code
STATUS_CODE_OK = 200
STATUS_CODE_ACCEPTED = 202
STATUS_CODE_DUPPLICATED = 203

STATUS_CODE_BAD_REQUEST = 400
STATUS_CODE_FORBIDDEN = 403
STATUS_CODE_NOT_FOUND= 404
STATUS_CODE_METHOD_NOT_ALLOWED = 405
STATUS_CODE_TIMEOUT = 408

STATUS_CODE_SERVER_ERROR = 500
STATUS_CODE_NOT_IMPLEMENTED = 501
STATUS_CODE_SERVICE_UNAVAILABLE = 503

# New Status code for package
STATUS_CODE_ON_PRECESSING = 801
STATUS_CODE_IS_PROCESSED = 802
STATUS_CODE_IN_QUEUE = 803
STATUS_CODE_NONE = 804

STATUS_CODE_UNKWOWN_ERROR = 900

# AURORA STATUS
AURORA_STATUS_DISABLED = 1
AURORA_STATUS_ENABLED = 0

# MULTI AURORA STATUS
AURORA_STATUS_DISABLED_FROM_TASK = b'0000001'
AURORA_STATUS_DISABLED_FROM_BAK = b'0000100'
AURORA_STATUS_DISABLED_FROM_DBA = b'0000010'
AURORA_STATUS_DISABLED_FROM_LOCK = b'0001000'
AURORA_STATUS_ENABLED_FROM_TASK = b'1111110'
AURORA_STATUS_ENABLED_FROM_BAK = b'1111011'
AURORA_STATUS_ENABLED_FROM_DBA = b'1111101'
AURORA_STATUS_ENABLED_FROM_LOCK = b'1110111'



RDS_GLOBAL_ACCESS_DENY = 3
RDS_GLOBAL_ACCESS_READONLY = 4
RDS_GLOBAL_ACCESS_NORMAL = 5
RDS_GLOBAL_ACCESS_DISK_FULL_LOCK = 6

# Task error code
ERROR_UNKNOWN = 'unknown'

# BACKUP STATUS
BACKUP_STATUS_DISABLED = 0
BACKUP_STATUS_ENABLED = 1

# aurora_switch_log switch_status
AURORA_SWITCH_SUCCESS = 1
AURORA_SWITCH_FAIL = 0

####################### ERROR_CODES FOR TASK_QUEUE #########################
#e.g.: ERR_CODE = TASK_TYPE_GEN + ERR_TYPE_DB + ERR_SUMMARY_MYSQL
#level one: role
ERR_ROLE_DBA = 'dba.'
ERR_ROLE_DEV = 'dev.'
ERR_ROLE_USER = 'user.'

##level two:error summary
ERR_SUMMARY_MYSQL = 'mysql.' #mysql error
ERR_SUMMARY_MSSQL = 'mssql.' #mssql error
ERR_SUMMARY_PGSQL = 'pgsql.' #pgsql error
ERR_SUMMARY_MONGO = 'mongo.' #mongo error
ERR_SUMMARY_REDIS = 'redis.' #redis error
ERR_SUMMARY_SCODE = 'scode.' #source_code_group error
ERR_SUMMARY_TASK = 'task.' #task error
ERR_SUMMARY_BACKUP = 'backup.' #backup error

##level three:error reason
# ERR_REASON_SLAVE_ACCESS_DENIED
ERR_REASON_CMD_FAIL = 'cmd_failed'
ERR_REASON_IO_THREAD_STOP = 'io_thread_stopped'
ERR_REASON_SQL_THREAD_STOP = 'sql_thread_stopped'
ERR_REASON_IO_OR_SQL_THREAD_STOP = 'io_or_sql_thread_stopped'
ERR_REASON_SLAVE_SYNC_FAIL = 'slave_sync_fail'
ERR_REASON_SLAVE_EXIST_LAG = 'slave_exist_lag'
ERR_REASON_DISK_FULL = 'disk_full'
ERR_REASON_DATA_INCONSISTENCY = 'data_inconsistency'
ERR_REASON_MIRROR_STAT_ERROR = 'mirror_stat_error'
ERR_REASON_INTERNAL_ERROR = 'internal_error'
ERR_REASON_UNKNOWN = 'unknown_error'
ERR_REASON_TASK_CANCELED = 'task_is_canceled'
ERR_REASON_TASK_ERROR = 'task_error'
ERR_REASON_HAS_FOREGIN_KEY = 'has_foregin_key'
ERR_REASON_RESTART_SLAVE_FAIL = 'restart_slave_failed'
ERR_REASON_SRC_INS_INVALID = 'src_instance_invalid'
ERR_REASON_MIRROR_INS_INVALID = 'mirror_instance_invalid'
ERR_REASON_SRC_MASTER_INS_CHANGED = 'src_master_instance_changed'
ERR_REASON_SRC_MIRROR_INS_IN_SAME_HOST = 'src_mirror_ins_in_same_host'
ERR_REASON_OUT_SWITCH_TIME_RANGE = 'out_switch_time_range'
ERR_REASON_SWITCH_INSTANCE_FAIL = 'switch_instance_fail'
ERR_REASON_INVALID_DDL_FAIL = 'ddl_is_invalid'
ERR_REASON_BVS_FAIL = 'backup_verification_service_fail'
#################### Detail error definition ##############
#mysql dba
ERR_CODE_DBA_MYSQL_CMD_FAIL = ERR_ROLE_DBA + ERR_SUMMARY_MYSQL + ERR_REASON_CMD_FAIL
ERR_CODE_DBA_MYSQL_IO_THREAD_STOP= ERR_ROLE_DBA + ERR_SUMMARY_MYSQL + ERR_REASON_IO_THREAD_STOP
ERR_CODE_DBA_MYSQL_SQL_THREAD_STOP= ERR_ROLE_DBA + ERR_SUMMARY_MYSQL + ERR_REASON_SQL_THREAD_STOP
ERR_CODE_DBA_MYSQL_IO_OR_SQL_THREAD_STOP= ERR_ROLE_DBA + ERR_SUMMARY_MYSQL + ERR_REASON_IO_OR_SQL_THREAD_STOP
ERR_CODE_DBA_MYSQL_SLAVE_SYNC_FAIL= ERR_ROLE_DBA + ERR_SUMMARY_MYSQL + ERR_REASON_SLAVE_SYNC_FAIL
ERR_CODE_DBA_MYSQL_SLAVE_EXIST_LAG= ERR_ROLE_DBA + ERR_SUMMARY_MYSQL + ERR_REASON_SLAVE_EXIST_LAG
ERR_CODE_DBA_MYSQL_DISK_FULL= ERR_ROLE_DBA + ERR_SUMMARY_MYSQL + ERR_REASON_DISK_FULL
ERR_CODE_DBA_MYSQL_DATA_INCONSISTENCY= ERR_ROLE_DBA + ERR_SUMMARY_MYSQL + ERR_REASON_DATA_INCONSISTENCY

#mssql dba
ERR_CODE_DBA_MSSQL_DISK_FULL= ERR_ROLE_DBA + ERR_SUMMARY_MSSQL + ERR_REASON_DISK_FULL
ERR_CODE_DBA_MSSQL_MIRROR_STAT_ERROR= ERR_ROLE_DBA + ERR_SUMMARY_MSSQL + ERR_REASON_MIRROR_STAT_ERROR
ERR_CODE_DBA_MSSQL_SLAVE_SYNC_FAIL= ERR_ROLE_DBA + ERR_SUMMARY_MSSQL + ERR_REASON_SLAVE_SYNC_FAIL
ERR_CODE_DBA_MSSQL_CMD_FAIL= ERR_ROLE_DBA + ERR_SUMMARY_MSSQL + ERR_REASON_CMD_FAIL

#pgsql dba
ERR_CODE_DBA_PGSQL_DISK_FULL= ERR_ROLE_DBA + ERR_SUMMARY_PGSQL + ERR_REASON_DISK_FULL
ERR_CODE_DBA_PGSQL_SLAVE_EXIST_LAG= ERR_ROLE_DBA + ERR_SUMMARY_PGSQL + ERR_REASON_SLAVE_EXIST_LAG

#mongodb dba
ERR_CODE_DBA_MONGO_DISK_FULL= ERR_ROLE_DBA + ERR_SUMMARY_MONGO + ERR_REASON_DISK_FULL

#mongodb dev
ERR_CODE_DEV_MONGO_BVS_FAIL= ERR_ROLE_DEV + ERR_SUMMARY_MONGO + ERR_REASON_BVS_FAIL

#dev
ERR_CODE_DEV_TASK_ERROR = ERR_ROLE_DEV + ERR_SUMMARY_TASK + ERR_REASON_TASK_ERROR
ERR_CODE_DEV_TASK_CANCEL = ERR_ROLE_DEV + ERR_SUMMARY_TASK + ERR_REASON_TASK_CANCELED
ERR_CODE_DEV_INTERNAL_ERROR = ERR_ROLE_DEV + ERR_SUMMARY_TASK + ERR_REASON_INTERNAL_ERROR
ERR_CODE_DEV_SRC_INS_INVALID = ERR_ROLE_DEV + ERR_SUMMARY_MYSQL + ERR_REASON_SRC_INS_INVALID
ERR_CODE_DEV_MIRROR_INS_INVALID = ERR_ROLE_DEV + ERR_SUMMARY_MYSQL + ERR_REASON_MIRROR_INS_INVALID
ERR_CODE_DEV_MYSQL_IO_OR_SQL_THREAD_STOP= ERR_ROLE_DEV + ERR_SUMMARY_MYSQL + ERR_REASON_IO_OR_SQL_THREAD_STOP
ERR_CODE_DEV_SRC_MASTER_INS_CHANGED = ERR_ROLE_DEV + ERR_SUMMARY_MYSQL + ERR_REASON_SRC_MASTER_INS_CHANGED
ERR_CODE_DEV_SRC_MIRROR_INS_IN_SAME_HOST = ERR_ROLE_DEV + ERR_SUMMARY_MYSQL + ERR_REASON_SRC_MIRROR_INS_IN_SAME_HOST
ERR_CODE_DEV_OUT_SWITCH_TIME_RANGE = ERR_ROLE_DEV + ERR_SUMMARY_MYSQL + ERR_REASON_OUT_SWITCH_TIME_RANGE

#user
ERR_CODE_USER_MYSQL_FOREGIN_KEY = ERR_ROLE_USER + ERR_SUMMARY_MYSQL + ERR_REASON_HAS_FOREGIN_KEY
ERR_CODE_USER_MYSQL_RESTART_SLAVE_FAIL = ERR_ROLE_USER + ERR_SUMMARY_MYSQL + ERR_REASON_RESTART_SLAVE_FAIL
ERR_CODE_USER_MYSQL_SWITCH_INSTACNE_FAIL = ERR_ROLE_USER + ERR_SUMMARY_MYSQL + ERR_REASON_SWITCH_INSTANCE_FAIL

ERR_CODE_USER_MYSQL_DDL_FAIL = ERR_ROLE_USER + ERR_SUMMARY_MYSQL + ERR_REASON_INVALID_DDL_FAIL
############################ Host health status ############################
HOST_RUNNING = 1
#2 is deperated
HOST_DOWN = 2

HOST_OFFLINE = 3
HOST_OFFLINE_NORMAL = 4

############################ Host Disk health status ############################
DISK_OFFLINE = 0
DISK_RUNNING = 1

############################ Host type ############################
D_SERIES_HOST = 0
S_SERIES_HOST = 1
ECS_SERIES_HOST = 2
# hybrid storage (ali_flash + sata -> bcache)
N_SERIES_HOST = 3
POLAR_SERRIES_HOST = 4

############################ service status ################################
PENGINE_SERVICE_OK = 1
PENGINE_SERVICE_CRITICAL = 2


################# conn_addr change log status ####################
CONN_ADDR_CHANGELOG_INIT = 0
CONN_ADDR_CHANGELOG_DONING = 1
CONN_ADDR_CHANGELOG_DONE = 2

CONN_ADDR_ACTION_ADD = 1
CONN_ADDR_ACTION_UPDATE = 2
CONN_ADDR_ACTION_DELETE = 3

############################ fcs service status ################################
INS_STATUS_CREATE = 0
INS_STATUS_RUNNING = 1
INS_STATUS_LOCK = 2
INS_STATUS_DELETE = 3
INS_STATUS_DELETED = 4
INS_STATUS_MIGRATE = 5
INS_STATUS_APPEND = 6
INS_STATUS_INIT = 7
INS_STATUS_SWITCHING = 8


RDSAPI_SUCCESS = "successful"
RDSAPI_DUPLICATE = "duplicate"
RDSAPI_ERROR = "rds api connection error"
RDSAPI_CAPACITY = "InsufficientResourceCapacity"

RDSAPI_BACKUPJOB_EXISTS = "BackupJobExists"

SLBAPI_SUCCESS = "successful"
SLBAPI_ERROR = "slb api connection error"

DNSAPI_SUCCESS = "OK\n"
DNSAPI_ERROR = "dns api connection error"

HA_PROXYAPI_CONNECTION_ERROR = "haproxy api connection error"

PROXY_CONNECTION_ERROR = "proxy api connection error"

EXTERNAL_TYPE_HAPROXY = 0
EXTERNAL_TYPE_JAEPROXY = 1
EXTERNAL_TYPE_LVS = 2

TABLE_STATUS_CREATE = 0
TABLE_STATUS_RUNNING = 1
TABLE_STATUS_MODIFY = 2
TABLE_STATUS_DELETE = 3
TABLE_STATUS_NODE_EXCEPTION = 4
TABLE_STATUS_EXCEPTION = 5

USER_PRIVILEGE = "DMLOnly"
ADMIN_PRIVILEGE = "ReadWrite"

############### instance resource config ################
RES_IOPS = 'max_iops'
RES_CPU_PERCENT = 'max_cpu_percent'
RES_CPU_SHARE = 'cpu_share'
RES_CONNECTION = 'max_conn'
RES_CPU_CORES = 'cpu_cores'

RES_GP_MASTER_CPU = "master_cpu"
RES_GP_MASTER_MEMORY = "master_memory"
RES_GP_MASTER_IOPS = "master_iops"
RES_GP_MASTER_DISK_MBPS = "master_disk_mbps"
RES_GP_MASTER_NETWORK = "master_network"
RES_GP_SEGMENT_CPU = "segment_cpu"
RES_GP_SEGMENT_MEMORY = "segment_memory"
RES_GP_SEGMENT_IOPS = "segment_iops"
RES_GP_SEGMENT_DISK_MBPS = "segment_disk_mbps"
RES_GP_SEGMENT_NETWORK = "segment_network"

RDS_VERIFY_USER_ID = 'internal_system'
RDS_VERIFY_UID = 'rds_controller'

RDS_USER_ID = 'rds'
RDS_UID = 'controller'

################ for migrate db job #####################
LOGIC_MIGRATE_TYPE = "logical"
PHYSICAL_MIGRATE_TYPE = "physical"
BACKUP_DATE_FORMAT = '%Y-%m-%d %H:%M:%S'
############## work for restore & remote trans ###########
BAKSET_TYPE_FULL = "full"
BAKSET_TYPE_INCREMENT = "increment"
ACTION_DOWNLOAD_BAKSET =  "download"
ACTION_RESTORE_BAKSET =  "restore"

# ms inconsist check task status
# ms check survival queue maxsize
MAX_SURVIVAL_QUEUE_SIZE = 1000000
# ms check task type
MS_CHECK_ROUTINE = 10
MS_CHECK_FROM_DBA = 20
MS_CHECK_FROM_TASK = 30
# ms check task status
MS_CHECK_STATUS_INIT = 0
MS_CHECK_STATUS_BEGIN = 1
MS_CHECK_STATUS_RUNNING = 2
MS_CHECK_STATUS_OK = 3
MS_CHECK_STATUS_FAILED = 4
MS_CHECK_STATUS_PAUSE = 5
MS_CHECK_STATUS_PAUSING = 6
MS_CHECK_STATUS_PAUSED = 7
MS_CHECK_STATUS_CLOSE = 8
MS_CHECK_STATUS_CLOSING = 9
MS_CHECK_STATUS_CLOSED = 10
# stop ms check code
EXIT_BECAUSE_PAUSED = 0
EXIT_BECAUSE_CLOSED = 1
EXIT_BECAUSE_MASTER_DELETED = 2
EXIT_BECAUSE_SLAVE_DELETED = 3
EXIT_BECAUSE_NOT_NEED = 4
EXIT_BECAUSE_LAST_CHUNK = 5
SHOULD_CONTINUAL_CHECK = 6
EXIT_BECAUSE_SLAVE_LAG = 7
# ms check default parameter
DEFAULT_IOPS_RATE = 0.05

############## system accounts ###########
SYSTEM_ACCOUNT_AURORA_PROXY = 'aurora_proxy'
SYSTEM_ACCOUNT_AURORA = 'aurora'
SYSTEM_ACCOUNT_RDS_SERVICE = 'rds_service'
ACCOUNT_BIZ_TYPE_SYSTEM = 'system'
ACCOUNT_BIZ_TYPE_SUPER = 'super'
ACCOUNT_BIZ_TYPE_OS = 'os'
ACCOUNT_BIZ_TYPE_SYNC = 'sync'
ACCOUNT_BIZ_TYPE_USERBIZ = 'userbiz'
SYSTEM_ACCOUNT_REPLICATE = 'replicator'
NORMAL_ACCOUNT = 1
READONLY_ACCOUNT = 2
BINLOG_READONLY_ACCOUNT = 3
BINLOG_SUPER_ACCOUNT = 4
#for jituan shangyun , now is deprated
TAO_SUPER_ACCOUNT = 5
#used for public yun
ALIYUN_SUPER_ACCOUNT = 6
PRIVILEDGE_TYPE_AURORA = 7
PRIVILEDGE_TYPE_ADMIN = 8
PRIVILEDGE_TYPE_INTERNAL = 9
PRIVILEDGE_TYPE_DATA_TRANSFER = 10
PRIVILEDGE_TYPE_RDS_SERVICE = 11
PRIVILEDGE_TYPE_OS_ADMIN = 12

PRIVILEDGE_TYPE_REPLICATE = 15

PRIVILEDGE_TYPE_OPENSEARCH = 16

PRIVILEDGE_TYPE_AURORA_PROXY = 17

PRIVILEDGE_TYPE_SUPER = 18

PARTITION_LEVEL_MAP = {
                       "4dbs_128bu":(4, 128),
                       "8dbs_128bu":(8, 128),
                       "16dbs_100bu":(16, 128),
                       "16dbs_128bu":(16, 128),
                       "32dbs_256bu":(32, 256),
                       "64dbs_256bu":(64, 256),
                       "64dbs_512bu":(64, 512),
                       "128dbs_256bu":(128, 256),
                       "128dbs_512bu":(128, 512),
                       "256dbs_512bu":(256, 512),
                       "256dbs_1024bu":(256, 1024),
                       "512dbs_1024bu":(512, 1024),
                       "512dbs_2048bu":(512, 2048),
                       "1024dbs_1024bu":(1024, 1024),
                       "1024dbs_2048bu":(1024, 2048)
                       }

PRIVILEDGE_TYPE_DBUSER = 1

RDS_INTERNAL_MARK = ' /* rds internal mark */ '

###########kind_code##############
KIND_CODE_NC = 0
KIND_CODE_ECS_VM = 1
KIND_CODE_DOCKER = 2
KIND_CODE_DOCKER_ECS_VM = 3
KIND_CODE_DOCKER_POLARDB = 6

##########docker restart policy##########
DOCKER_UPGRADE = 'upgrade'
DOCKER_COLD_RESTART = 'cold'
DOCKER_HOT_RESTART = 'hot'


############### Instance Role ###################
ROLE_MASTER = 0
ROLE_SLAVE = 1
ROLE_LOGGER = 2
ROLE_MONGO_HIDDEN = 3
ROLE_MONGO_READONLY = 4
ROLE_GP_SEGMENT = 16
ROLE_GP_SEGMENT_PRIMARY = 17
ROLE_GP_SEGMENT_MIRROR = 18


################# RW split var ############

RW_TYPE_NORMAL = 0
RW_TYPE_RW_SPLIT = 1
RW_TYPE_POLICY_SYS_DEF = 0
RW_TYPE_POLICY_USER_DEF = 1
RW_SPLIT_WEIGHT_POLICY = "rw_split_weight_policy"
RW_SPLIT_RO_WEIGHT = "rw_split_ro_weight"
RW_SPLIT_MASTER_WEIGHT = "rw_split_master_weight"
RW_SPLIT_MAX_DELAY_TIME = "rw_split_max_delay_time"
RW_SPLIT_MYSQL_56_MINOR_VERSION = "mysql56_20161123"

################## aurora_proxy account ######
AURORA_PROXY_56_MINOR_VERSION = "mysql56_20171113"
RDS_PROXY_USER_LIST = ["aurora_proxy"]
RDS_PROXY_USER = "aurora_proxy"
AURORA_PROXY_PARAM = "loose_rds_proxy_user_list"

####################FOR DOCKER==================
TUNNEL_SERVER_BAK_TYPE=125


class RestoreType(object):
    BAKSET = "0"
    TIME = "1"
    USER = "2"
    STANDBY = "4"
    BAKSET_OSS = "5"
    LASTEST = "8"    # restore to lastest time

#################### PetaData ==================
SCHEMA_BAK_READY = 0
SCHEMA_BAK_FINISHED = 0
SCHEMA_BAK_PREPARE = 1
SCHEMA_BAK_RUNNING = 2
SCHEMA_BAK_UPLOAD = 3
SCHEMA_BAK_FAILED = 4


#################### FOR stat backup check #############
DB_TYPE_MYSQL = 'mysql'
DB_TYPE_MSSQL = 'mssql'
DB_TYPE_PGSQL = 'pgsql'
DB_TYPE_PPAS = 'ppassql'
DB_TYPE_MONGODB = 'mongodb'
DB_TYPE_REDIS = 'redis'
DB_TYPE_GPDB = 'gpdb'
DB_TYPE_POLAR_MYSQL_RW = "polardb_mysql_rw"
DB_TYPE_POLAR_MYSQL_RO = "polardb_mysql_ro"
BACKUP_DB_TYPE_SET = (
    DB_TYPE_MYSQL,
    DB_TYPE_MSSQL,
    DB_TYPE_PGSQL,
    DB_TYPE_PPAS,
    DB_TYPE_MONGODB,
    DB_TYPE_REDIS,
    DB_TYPE_GPDB,
    DB_TYPE_POLAR_MYSQL_RW,
    DB_TYPE_POLAR_MYSQL_RO,
)


#########for slb #######
MAX_SLB_NODE_PER_INSERT = 15


#########system user for mysql series ###############
MYSQL_SYSTEM_USERS_LIST = ["system user","rds_service", "aliyun_root","event_scheduler","unauthenticated user", "root"]


########PERF_FREQUENCY##############
RESOURCE_PERF_FREQUENCY_DEFAULT = "300"
RESOURCE_PERF_FREQUENCY_VIP_INS_DEFAULT = "60"
PREF_FREQUENCY_VIP_INS_ADVANCE = "5"

########PERF_PARAM##################
PERF_FREQUENCY = "frequency"
PERF_MYSQL_MEMORY_SIZE_RULE = "PERF_MYSQL_MEMORY_SIZE_RULE"

#########PARAM_GROUPS############
PARAM_GROUP_TYPE_BACK_UP = 2

############# use kms encrypt ssl in apc env  #############
CLUSTER_PARAM_KMSFORSSL = "kms_encrypt_ssl"

########################### kms encrypt data 加密后的密文####
######################### 见kmsService encrypt 接口返回格式  ###########
CIPHER_BLOB = 'CiphertextBlob'

# common biz pipeline biz code
GENERIC_PENGINE_REIGISTER_BIZ_CODE = 'generic'


# common commands
CMD_EXECUTE = "execute"
CMD_REPORT = "report"
CMD_PING = "ping"
CMD_DELETE_TASK = 'delete_task'
CMD_START_SERVICE = 'start'
CMD_STOP_SERVICE = 'stop'
CMD_LIST_TASKS = 'list'
CMD_START_PIPELINE = "start_pipeline"
CMD_REGIST_PENGINE = 'regist_pengine'
CMD_REPORT_PENGINE = 'report_pengine'
